---
title: "R Notebook"
output: html_notebook
---

Load data

```{r}
rm(list = ls())
source('script_loaddata.R')
```

Use SEM library

```{r}
library(sem)
library(polycor)
```

correlation matrix

```{r}
subdata <- data[c('PC1', 'Area', 'Distance_to_Nearest','Aall', 'Pall', 'Hall')]
covdata <- cov(subdata)
```


model and SEM 

```{r}
model0D <- specifyModel(file="./model/mod0D.txt", endog.variances=TRUE)
semHerb <- sem(model0D, covdata, N=38, data)

summary(semHerb)
#temp<-summary(semHerb)
#$AIC
#temp$BIC
```

```{r}
spp <- data[c('Aall', 'Pall', 'Hall')]
cor(spp)
```

## reverse the H --> P link

```{r}
model0E <- specifyModel(file="./model/mod0E.txt", endog.variances=TRUE)
semHerb <- sem(model0E, covdata, N=38, data)

summary(semHerb)
```

## model of no species interaction

```{r}
model0F <- specifyModel(file="./model/mod0F.txt", endog.variances=TRUE)
semHerb <- sem(model0F, covdata, N=38, data)

summary(semHerb)
```

# force a A --> H link

```{r}
model0G <- specifyModel(file="./model/mod0G.txt", endog.variances=TRUE)
semHerb <- sem(model0G, covdata, N=38, data)

summary(semHerb)
```


